config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :custom_destroy_user_session
    root to: 'homes#top', as: :custom_root # ログアウト後に表示するページのルートパスを指定する
  end
  get 'home/about', to: 'homes#about'
  resources :users
  resources :posts do
    resources :post_comments, only: [:destroy, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :post_image
  has_many :post_comments, dependent: :destroy
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :user_image
  has_many_attached :Post
  has_many :post_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user) # ログインした直後は、ユーザーの詳細ページに遷移
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "投稿が保存されました。"
      redirect_to posts_path
    else
      flash.now[:alert] = "投稿の保存に失敗しました。"
      puts @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.includes(:user)
    @comment_users = @post_comments.map(&:user).uniq
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :location, :description, :post_image, :latitude, :longitude, :station, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.all
  end

  def index
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :user_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <p>footer</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <span>app_name</span>
  <% if user_signed_in? %>
      <%= link_to 'Users', users_path %>
      <%= link_to 'Posts', posts_path %>
      <%= link_to 'My page', user_path(current_user) %>
      <%= link_to 'Log out', custom_destroy_user_session_path, method: :delete %>
  <% else %>
      <a href="/home/about">About</a>
      <%= link_to 'Sign up', new_user_registration_path %>
      <%= link_to 'Log in', new_user_session_path %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RrDateApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>編集</h2>
  <%= form_with model:@post, local: true do |f| %>

    <h4>タイトル</h4>
    <%= f.text_field :title%>

    <h4>お勧めする場所</h4>
    <%= f.text_field :location%>

    <h4>説明文</h4>
    <%= f.text_field :description%>

    <h4>写真</h4>
    <%= f.file_field :post_image %>

    <h4>最寄駅</h4>
    <%= f.text_field :station%>

    <h4><%= f.submit '投稿' %></h4>

  <% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post_path(post) do %>
    <h3><%= post.title %></h3>
  <% end %>
  <p><%= post.description %></p>
  <%= post.location %>
  <% if post.post_image.present? %>
    <%= image_tag post.post_image, size: "100x100" %>
  <% else %>
    <%= image_tag "default-image.jpg", size: "100x100" %>
  <% end %>
  <p><%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %></p>

  <!-- 他の投稿の属性を表示するためのコードを追加 -->
<% end %>

app/views/posts/new.html.erb
<h2>新しい記録</h2>
  <%= form_with model:@post, local: true do |f| %>

    <h4>タイトル</h4>
    <%= f.text_field :title%>

    <h4>お勧めする場所</h4>
    <%= f.text_field :location%>

    <h4>説明文</h4>
    <%= f.text_field :description%>

    <h4>写真</h4>
    <%= f.file_field :post_image %>

    <h4>最寄駅</h4>
    <%= f.text_field :station%>

    <h4><%= f.submit '投稿' %></h4>

  <% end %>

app/views/posts/show.html.erb
<% if @post.post_image.present? %>
  <%= image_tag @post.post_image, size: "100x100" %>
<% else %>
  <%= image_tag "default-image.jpg", size: "100x100" %>
<% end %>

<%= @post.location %>
<%= @post.title %>
<%= @post.description %>
<%= @post.station %>
<%= link_to "編集", edit_post_path(@post) %>
<%= button_to "削除", post_path(@post), method: :delete %>

<p>コメント件数：<%= @post.post_comments.count %></p>
<% @post.post_comments.each do |post_comment| %>
  <p><%= image_tag post_comment.user.user_image, size: "50x50" %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>

  <% if post_comment.user == current_user %>
    <%= form_with(model: [post_comment.post, post_comment], url: post_post_comment_path(post_comment.post, post_comment), local: true, method: :delete) do |f| %>
      <%= f.submit "削除", data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  <% end %>

<% end %>

<%= form_with(model:[@post, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>

<h2>gmap</h2>
<input id="address" type="textbox" value="<%= @post.location %>">
<input type="button" value="Encode" onclick="codeAddress()">

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map
let geocoder

const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });
}


</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

app/views/users/edit.html.erb
<h2 class="text-center mb-4">プロフィール編集</h2>
  <%= form_with model:@user, local: true do |f| %>
      <h4>Name</h4>
      <%= f.text_field :name %>

      <h4>プロフィール画像</h4>
      <%= f.file_field :user_image %>

    <div class="text-center">
      <%= f.submit '更新' %>
    </div>
  <% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>

<%= @user.name %>
<%= link_to 'プロフィール編集', edit_user_path %>
<%= link_to '新規投稿', new_post_path %>
<% if @user.user_image.present? %>
  <%= image_tag @user.user_image, size: "100x100" %>
<% else %>
  <%= image_tag "default-image.jpg", size: "100x100" %>
<% end %>

<% @posts.each do |post| %>
  <%= link_to post_path(post) do%>
    <h3><%= post.title %></h3>
  <% end %>
  <p><%= post.description %></p>
  <%= post.location %>
  <% if post.post_image.present? %>
    <%= image_tag post.post_image, size: "100x100" %>
  <% else %>
    <%= image_tag "default-image.jpg", size: "100x100" %>
  <% end %>
<% end %>